/*
 * Power API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lowell@lanl.gov
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// AggregationServiceActionsAggregationServiceResetPost - Request aggregate system reset
func (s *DefaultApiService) AggregationServiceActionsAggregationServiceResetPost(ctx context.Context, aggregationResetBody AggregationResetBody) (ImplResponse, error) {
	// TODO - update AggregationServiceActionsAggregationServiceResetPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, AggregationResetBody{}) or use other options such as http.Ok ...
	//return Response(200, AggregationResetBody{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AggregationServiceActionsAggregationServiceResetPost method not implemented")
}

// ComputerSystemsGet - Get computer systems
func (s *DefaultApiService) ComputerSystemsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ComputerSystemsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ComputerSystemCollection{}) or use other options such as http.Ok ...
	//return Response(200, ComputerSystemCollection{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ComputerSystemsGet method not implemented")
}

// ComputerSystemsNameActionsComputerSystemResetPost - Request system reset
func (s *DefaultApiService) ComputerSystemsNameActionsComputerSystemResetPost(ctx context.Context, name string, resetRequestBody ResetRequestBody) (ImplResponse, error) {
	// TODO - update ComputerSystemsNameActionsComputerSystemResetPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ResetRequestBody{}) or use other options such as http.Ok ...
	//return Response(200, ResetRequestBody{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ComputerSystemsNameActionsComputerSystemResetPost method not implemented")
}

// ComputerSystemsNameGet - Get a specific computer system state
func (s *DefaultApiService) ComputerSystemsNameGet(ctx context.Context, name string) (ImplResponse, error) {
	// TODO - update ComputerSystemsNameGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ComputerSystem{}) or use other options such as http.Ok ...
	//return Response(200, ComputerSystem{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ComputerSystemsNameGet method not implemented")
}

