/*
 * Power API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lowell@lanl.gov
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// ErrorError - Properties that describe the error
type ErrorError struct {

	// Response code
	Code string `json:"code"`

	// A human-readable error message string
	Message string `json:"message"`
}
