/*
 * Power API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// ResetRequestBody - Reset request
type ResetRequestBody struct {

	ResetType ResetType `json:"ResetType"`
}
