/*
 * Power API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lowell@lanl.gov
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// ComputerSystem - A single computer system with power state
type ComputerSystem struct {

	// An id is a URI-reference for the object
	Id string `json:"id"`

	// The name is the unique name identifier for the ComputerSystem. This is used to reference the system in the API. 
	Name string `json:"name"`

	PowerState PowerState `json:"powerState,omitempty"`
}
