/*
 * Power API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lowell@lanl.gov
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// PowerState : Power state for a component
type PowerState string

// List of PowerState
const (
	POWERSTATE_ON PowerState = "On"
	POWERSTATE_OFF PowerState = "Off"
)
