/*
 * Power API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: lowell@lanl.gov
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// ComputerSystemCollection - A collection of computer systems
type ComputerSystemCollection struct {

	// An id is a URI-reference for the object
	Id string `json:"id,omitempty"`

	// Human-readable name for the collection
	Name string `json:"name,omitempty"`

	// Collection of ComputerSystem objects
	Systems []ComputerSystem `json:"systems,omitempty"`
}
