/*
 * Power API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	api "github.com/jlowellwofford/powermanapi/cmd/powermanapi/api"
)

func main() {
	log.Printf("Server started")

	PowermanApiService := api.NewPowermanApiService("127.0.0.1", 10101)
	DefaultApiController := api.NewDefaultApiController(PowermanApiService)

	router := api.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8269", router))
}
