/*
 * Power API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package powerapi

import (
	"encoding/json"
	"fmt"
)

// ResetType the model 'ResetType'
type ResetType string

// List of ResetType
const (
	RESETTYPE_ON ResetType = "On"
	RESETTYPE_FORCE_OFF ResetType = "ForceOff"
	RESETTYPE_GRACEFUL_SHUTDOWN ResetType = "GracefulShutdown"
	RESETTYPE_GRACEFUL_RESTART ResetType = "GracefulRestart"
	RESETTYPE_FORCE_RESTART ResetType = "ForceRestart"
	RESETTYPE_NMI ResetType = "Nmi"
	RESETTYPE_FORCE_ON ResetType = "ForceOn"
	RESETTYPE_PUSH_POWER_BUTTON ResetType = "PushPowerButton"
	RESETTYPE_POWER_CYCLE ResetType = "PowerCycle"
)

func (v *ResetType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResetType(value)
	for _, existing := range []ResetType{ "On", "ForceOff", "GracefulShutdown", "GracefulRestart", "ForceRestart", "Nmi", "ForceOn", "PushPowerButton", "PowerCycle",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ResetType", value)
}

// Ptr returns reference to ResetType value
func (v ResetType) Ptr() *ResetType {
	return &v
}

type NullableResetType struct {
	value *ResetType
	isSet bool
}

func (v NullableResetType) Get() *ResetType {
	return v.value
}

func (v *NullableResetType) Set(val *ResetType) {
	v.value = val
	v.isSet = true
}

func (v NullableResetType) IsSet() bool {
	return v.isSet
}

func (v *NullableResetType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetType(val *ResetType) *NullableResetType {
	return &NullableResetType{value: val, isSet: true}
}

func (v NullableResetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

