/*
 * Power API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package powerapi

import (
	"encoding/json"
)

// ResetRequestBody Reset request
type ResetRequestBody struct {
	ResetType ResetType `json:"ResetType"`
	AdditionalProperties map[string]interface{}
}

type _ResetRequestBody ResetRequestBody

// NewResetRequestBody instantiates a new ResetRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetRequestBody(resetType ResetType, ) *ResetRequestBody {
	this := ResetRequestBody{}
	this.ResetType = resetType
	return &this
}

// NewResetRequestBodyWithDefaults instantiates a new ResetRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetRequestBodyWithDefaults() *ResetRequestBody {
	this := ResetRequestBody{}
	return &this
}

// GetResetType returns the ResetType field value
func (o *ResetRequestBody) GetResetType() ResetType {
	if o == nil  {
		var ret ResetType
		return ret
	}

	return o.ResetType
}

// GetResetTypeOk returns a tuple with the ResetType field value
// and a boolean to check if the value has been set.
func (o *ResetRequestBody) GetResetTypeOk() (*ResetType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ResetType, true
}

// SetResetType sets field value
func (o *ResetRequestBody) SetResetType(v ResetType) {
	o.ResetType = v
}

func (o ResetRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ResetType"] = o.ResetType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ResetRequestBody) UnmarshalJSON(bytes []byte) (err error) {
	varResetRequestBody := _ResetRequestBody{}

	if err = json.Unmarshal(bytes, &varResetRequestBody); err == nil {
		*o = ResetRequestBody(varResetRequestBody)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "ResetType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResetRequestBody struct {
	value *ResetRequestBody
	isSet bool
}

func (v NullableResetRequestBody) Get() *ResetRequestBody {
	return v.value
}

func (v *NullableResetRequestBody) Set(val *ResetRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableResetRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableResetRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetRequestBody(val *ResetRequestBody) *NullableResetRequestBody {
	return &NullableResetRequestBody{value: val, isSet: true}
}

func (v NullableResetRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


